apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app.kubernetes.io/name: echo-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: echo-service
  sessionAffinity: None
